# Generated by Django 5.1.2 on 2025-12-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_testimonial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(help_text='Maximum 30 characters', max_length=30),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_picture',
            field=models.ImageField(help_text='Recommended size: 100 × 100 pixels', upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(help_text='Maximum 100 characters', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(help_text='Maximum 20 characters', max_length=20),
        ),
    ]
