# Generated by Django 5.1.2 on 2025-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_testimonial_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincontent', models.CharField(max_length=200)),
                ('locationtodisplay', models.TextField(help_text='Paste Google Map embed URL or iframe src')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
