# Generated by Django 5.1.2 on 2025-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='locationtodisplay',
            field=models.TextField(help_text='Paste Google Maps iframe OR only the src URL'),
        ),
    ]
