# Generated by Django 5.1.2 on 2025-12-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_contactpage_locationtodisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Enter service name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description about the service')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
