# Generated by Django 5.1.2 on 2025-12-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_typesofservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesofservice',
            name='description',
            field=models.TextField(help_text='Short description about the service', max_length=100),
        ),
        migrations.AlterField(
            model_name='typesofservice',
            name='service_name',
            field=models.CharField(help_text='Enter service name', max_length=30, unique=True),
        ),
    ]
