# Generated by Django 5.1.2 on 2025-12-15 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_typesofservice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField(help_text='Detailed service description')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='website.typesofservice')),
            ],
        ),
    ]
