# Generated by Django 5.1.2 on 2025-12-15 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_servicecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecontent',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='servicecontent',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='servicecontent',
            name='image_5',
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='description_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='description_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='description_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='description_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.typesofservice'),
        ),
    ]
