# Generated by Django 5.1.2 on 2025-12-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_servicecontent_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontent',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='website.typesofservice'),
        ),
    ]
