# Generated by Django 5.1.2 on 2025-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_servicecontent_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontent',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
