# Generated by Django 5.1.2 on 2025-12-16 06:29

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_servicecontent_image_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter team member full name', max_length=100)),
                ('designation', models.CharField(help_text='Enter team member designation (e.g., Manager, Developer)', max_length=100)),
                ('image', models.ImageField(help_text='Upload square image (400 x 400 pixels)', upload_to='team/', validators=[website.models.validate_team_image])),
                ('facebook', models.URLField(blank=True, help_text='Facebook profile link', null=True, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.URLField(blank=True, help_text='Twitter (X) profile link', null=True, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile link', null=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this member from website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
    ]
