# Generated by Django 5.1.2 on 2025-12-16 07:21

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_quote', models.CharField(help_text='Main heading or quote', max_length=200)),
                ('image', models.ImageField(help_text='Upload image with size 800 x 800 pixels', upload_to='features/', validators=[website.models.validate_800x800])),
                ('sub_title1', models.CharField(help_text='Unique subtitle 1', max_length=100, unique=True)),
                ('icon1', models.CharField(help_text='Font Awesome icon name only (example: truck, clock, shield)', max_length=30)),
                ('short_description1', models.CharField(help_text='Short description 1', max_length=150)),
                ('sub_title2', models.CharField(help_text='Unique subtitle 2', max_length=100, unique=True)),
                ('icon2', models.CharField(help_text='Font Awesome icon name only', max_length=30)),
                ('short_description2', models.CharField(help_text='Short description 2', max_length=150)),
                ('sub_title3', models.CharField(help_text='Unique subtitle 3', max_length=100, unique=True)),
                ('icon3', models.CharField(help_text='Font Awesome icon name only', max_length=30)),
                ('short_description3', models.CharField(help_text='Short description 3', max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
