# Generated by Django 5.1.2 on 2025-12-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='short_description',
            field=models.CharField(help_text='Short description about the company (shown at the end)', max_length=150),
        ),
    ]
