# Generated by Django 5.1.2 on 2025-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_aboutus_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='page_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/headers/'),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/headers/'),
        ),
    ]
