# Generated by Django 5.1.2 on 2025-12-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_contactpage_page_header_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page_header_image',
        ),
    ]
