# Generated by Django 5.1.2 on 2025-12-16 10:57

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_contactpage_page_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarPageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page_image', models.ImageField(blank=True, help_text='Upload About page banner image (Exact size: 1920 x 1080)', null=True, upload_to='navbar/', validators=[website.models.validate_1920_1080])),
                ('about_page_description', models.TextField(blank=True, help_text='Optional description for About page banner', null=True)),
                ('gallery_page_image', models.ImageField(blank=True, help_text='Upload Gallery page banner image (Exact size: 1920 x 1080)', null=True, upload_to='navbar/', validators=[website.models.validate_1920_1080])),
                ('gallery_page_description', models.TextField(blank=True, help_text='Optional description for Gallery page banner', null=True)),
                ('contact_page_image', models.ImageField(blank=True, help_text='Upload Contact page banner image (Exact size: 1920 x 1080)', null=True, upload_to='navbar/', validators=[website.models.validate_1920_1080])),
                ('contact_page_description', models.TextField(blank=True, help_text='Optional description for Contact page banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
