# Generated by Django 5.1.2 on 2025-12-16 12:57

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_servicecontent_page_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarpageimages',
            name='why_choose_us_description',
            field=models.TextField(blank=True, help_text="Optional description for 'Why Choose Us' section", null=True),
        ),
        migrations.AddField(
            model_name='navbarpageimages',
            name='why_choose_us_image',
            field=models.ImageField(blank=True, help_text="Upload 'Why Choose Us' section image (Exact size: 1920 x 1080)", null=True, upload_to='navbar/', validators=[website.models.validate_1920_1080]),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
