# Generated by Django 5.1.2 on 2025-12-16 13:00

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_servicecontent_page_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='detail_content',
            new_name='why_choose_us',
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
