# Generated by Django 5.1.2 on 2025-12-17 11:53

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_servicecontent_page_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofservice',
            name='image',
            field=models.ImageField(default='services/default.png', help_text='Upload image with exact size 500 x 300 px', upload_to='services/', validators=[website.models.validate_image_500x300]),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
