# Generated by Django 5.1.2 on 2025-12-17 16:59

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_servicecontent_page_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter slider title', max_length=200)),
                ('description', models.TextField(help_text='Short description for the slider')),
                ('quote', models.CharField(help_text='Quote text shown on slider', max_length=255)),
                ('highlight_word', models.CharField(help_text='Word to highlight inside the quote', max_length=50)),
                ('image', models.ImageField(help_text='Upload image (Exact size: 1920 x 1080 px)', upload_to='sliders/', validators=[website.models.validate_1920x1080])),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this slider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
