# Generated by Django 5.1.2 on 2025-12-17 17:10

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_homepageslider_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='highlight_word',
            field=models.CharField(help_text='Word to highlight inside the quote', max_length=10),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='quote',
            field=models.CharField(help_text='Quote text shown on slider', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
