# Generated by Django 5.1.2 on 2025-12-17 17:18

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_alter_homepageslider_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='title',
            field=models.CharField(help_text='Enter slider title', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
