# Generated by Django 5.1.2 on 2025-12-17 17:23

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_homepageslider_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageslider',
            old_name='quote',
            new_name='quote_before',
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='quote_after',
            field=models.CharField(default='& Solution', help_text='Quote text shown on slider', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
