# Generated by Django 5.1.2 on 2025-12-18 11:59

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_rename_quote_homepageslider_quote_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarpageimages',
            name='error_page_description',
            field=models.TextField(blank=True, help_text='Optional description for Contact page banner', null=True),
        ),
        migrations.AddField(
            model_name='navbarpageimages',
            name='error_page_image',
            field=models.ImageField(blank=True, help_text='Upload Contact page banner image (Exact size: 1920 x 1080)', null=True, upload_to='navbar/', validators=[website.models.validate_1920_1080]),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Upload service page header image (Exact size: 1920 x 1080)', null=True, upload_to='services/headers/', validators=[website.models.validate_1920_1080]),
        ),
    ]
