# Generated by Django 5.1.2 on 2025-12-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailConfiguration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toemail',
            name='send_ImgId',
        ),
        migrations.RemoveField(
            model_name='toemail',
            name='send_otp',
        ),
    ]
