# Generated by Django 5.1.2 on 2025-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailConfiguration', '0002_remove_toemail_send_imgid_remove_toemail_send_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='service_type',
            field=models.CharField(blank=True, choices=[('air_freight', 'Air Freight'), ('land_freight', 'Land Freight'), ('ocean_freight', 'Ocean Freight'), ('train_freight', 'Train Freight'), ('warehouse_clearance', 'Warehouse Clearance')], max_length=50, null=True),
        ),
    ]
