# Generated by Django 5.1.2 on 2025-12-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailConfiguration', '0003_remove_clientmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessage',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
