# Generated by Django 5.1.2 on 2025-12-11 18:05

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload your logo (PNG only)', upload_to='logos/', validators=[settings.models.validate_png])),
            ],
            options={
                'verbose_name': 'Logo Setting',
                'verbose_name_plural': 'Logo Settings',
            },
        ),
    ]
