# Generated by Django 5.1.2 on 2025-12-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logosettings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
