# Generated by Django 5.1.2 on 2025-12-12 08:08

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_logosettings_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=20, validators=[settings.models.validate_contact_number])),
                ('email', models.EmailField(max_length=254, validators=[settings.models.validate_email_address])),
                ('twitter', models.URLField(blank=True, null=True, validators=[settings.models.validate_url])),
                ('instagram', models.URLField(blank=True, null=True, validators=[settings.models.validate_url])),
                ('youtube', models.URLField(blank=True, null=True, validators=[settings.models.validate_url])),
                ('linkedin', models.URLField(blank=True, null=True, validators=[settings.models.validate_url])),
                ('facebook', models.URLField(blank=True, null=True, validators=[settings.models.validate_url])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Detail',
                'verbose_name_plural': 'Company Details',
            },
        ),
    ]
