# Generated by Django 5.1.2 on 2025-12-12 08:27

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_companydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', colorfield.fields.ColorField(default='#FF3E41', image_field=None, max_length=25, samples=None)),
                ('secondary', colorfield.fields.ColorField(default='#51CFED', image_field=None, max_length=25, samples=None)),
                ('light', colorfield.fields.ColorField(default='#F8F2F0', image_field=None, max_length=25, samples=None)),
                ('dark', colorfield.fields.ColorField(default='#060315', image_field=None, max_length=25, samples=None)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color Setting',
                'verbose_name_plural': 'Color Settings',
            },
        ),
    ]
