# Generated by Django 5.1.2 on 2025-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_colorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='logosettings',
            name='company_name',
            field=models.CharField(default='Capricon', help_text='Enter your company name', max_length=100),
        ),
    ]
