# Generated by Django 5.1.2 on 2025-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_logosettings_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='companyname',
            field=models.CharField(max_length=30),
        ),
    ]
