# Generated by Django 5.1.2 on 2025-12-13 20:13

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_companydetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logosettings',
            name='logo',
            field=models.ImageField(help_text='Upload your logo (PNG only, 1215x665 pixels)', upload_to='logos/', validators=[settings.models.validate_png, settings.models.validate_logo_dimensions]),
        ),
    ]
