# Generated by Django 5.1.2 on 2025-12-17 13:06

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_logosettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logosettings',
            name='title_logo',
            field=models.ImageField(blank=True, help_text='Upload title logo (PNG only, 32 x 32 px)', null=True, upload_to='logos/title/', validators=[settings.models.validate_png, settings.models.validate_title_logo_dimensions]),
        ),
    ]
