"""
Django settings for logistic project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rol-(%)u6&u2ge*hs33$d!lum$+4srm&o%-+qlt2nvb_n0!-k0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    ".onrender.com",
    "127.0.0.1",
    "localhost",
    "capricornshippingqatar.com",
    "www.capricornshippingqatar.com",
]




# Application definition

INSTALLED_APPS = [
    "jazzmin",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colorfield',
    'website',
    'settings',
    'EmailConfiguration',
]

MIDDLEWARE = [
    
    "whitenoise.middleware.WhiteNoiseMiddleware",
    
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'logistic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # or add a global templates folder if needed
        'APP_DIRS': True,  # must be True to use app-level templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]


WSGI_APPLICATION = 'logistic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_TZ = True
USE_L10N = False

TIME_FORMAT = 'H:i:s'            # 24-hour time
DATETIME_FORMAT = 'd-m-Y H:i:s'  # 24-hour datetime



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# settings.py

# Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "CapriconShipping Admin",  # Title on browser tab
    "site_header": "CapriconShipping",       # Header in admin
    "site_brand": "CapriconShipping",        # Brand text in top-left
    "site_logo": "logos/seo title png.png",  # Path to your logo (inside static folder)
    "login_logo": "logos/logo128.png",   # Logo on login page
    "login_logo_dark": None,         # Optional dark logo
    "site_icon": "logos/seo title png.png",       # Favicon
    "welcome_sign": "Welcome to Capricon Admin",
    "copyright": "Capricon © 2025",
    "search_model": "auth.User",     # Model to search in admin search bar
    "user_avatar": None,             # Optional user avatar

    # UI tweaks
    "show_ui_builder": True,         # Show UI customization panel
    "changeform_format": "horizontal_tabs",  # Form layout style
}



